# Generated by Django 4.2.4 on 2023-08-20 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='bouquets/')),
                ('height', models.DecimalField(decimal_places=1, max_digits=5)),
                ('width', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowershop_bot.bouquet')),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='flowershop_bot.bouquet')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowershop_bot.item')),
            ],
        ),
        migrations.AddField(
            model_name='bouquet',
            name='composition',
            field=models.ManyToManyField(through='flowershop_bot.Composition', to='flowershop_bot.item'),
        ),
    ]
