# Generated by Django 4.2.4 on 2023-08-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
