# Generated by Django 4.2.4 on 2023-08-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop_bot', '0002_composition_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='height',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='width',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
