# Generated by Django 4.2.4 on 2023-08-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop_bot', '0003_alter_bouquet_height_alter_bouquet_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='bouquet',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
