# Generated by Django 4.2.4 on 2023-08-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop_bot', '0004_bouquet_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(choices=[('wedding', 'Свадьба'), ('birthday', 'День рождения'), ('no_occasion', 'Без повода')], max_length=20)),
                ('price_range', models.CharField(choices=[('under-1000', 'До 1 000 руб'), ('1000-5000', '1 000 - 5 000 руб'), ('over-5000', 'от 5 000 руб'), ('no-matter', 'Не имеет значения')], max_length=20)),
                ('bouquets', models.ManyToManyField(related_name='occasions', to='flowershop_bot.bouquet')),
            ],
        ),
    ]
