# Generated by Django 4.2.4 on 2023-08-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop_bot', '0005_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=200)),
                ('price_range', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bouquet',
            name='quiz_steps',
            field=models.ManyToManyField(blank=True, related_name='bouquets', to='flowershop_bot.quizstep'),
        ),
    ]
