# Generated by Django 4.2.4 on 2023-08-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowershop_bot', '0006_quizstep_bouquet_quiz_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bouquet',
            name='quiz_steps',
        ),
        migrations.DeleteModel(
            name='QuizStep',
        ),
    ]
